# -*- coding: utf-8 -*-

#
# Created by: PyQt5 UI code generator 5.15.6
#



from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(321, 423)
        Window.setMinimumSize(QtCore.QSize(321, 0))
        Window.setMaximumSize(QtCore.QSize(321, 423))
        Window.setAutoFillBackground(False)
        Window.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(Window)
        self.centralwidget.setObjectName("centralwidget")
        self.inputField = QtWidgets.QLineEdit(self.centralwidget)
        self.inputField.setEnabled(False)
        self.inputField.setGeometry(QtCore.QRect(10, 10, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(16)
        self.inputField.setFont(font)
        self.inputField.setText("0")
        self.inputField.setMaxLength(24)
        self.inputField.setObjectName("inputField")
        self.clearBtn = QtWidgets.QPushButton(self.centralwidget)
        self.clearBtn.setGeometry(QtCore.QRect(10, 60, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(16)
        self.clearBtn.setFont(font)
        self.clearBtn.setObjectName("clearBtn")
        self.delBtn = QtWidgets.QPushButton(self.centralwidget)
        self.delBtn.setGeometry(QtCore.QRect(170, 60, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(16)
        self.delBtn.setFont(font)
        self.delBtn.setObjectName("delBtn")
        self.divisionBtn = QtWidgets.QPushButton(self.centralwidget)
        self.divisionBtn.setGeometry(QtCore.QRect(250, 130, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(16)
        self.divisionBtn.setFont(font)
        self.divisionBtn.setObjectName("divisionBtn")
        self.numNine = QtWidgets.QPushButton(self.centralwidget)
        self.numNine.setGeometry(QtCore.QRect(170, 130, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(16)
        self.numNine.setFont(font)
        self.numNine.setObjectName("numNine")
        self.numSeven = QtWidgets.QPushButton(self.centralwidget)
        self.numSeven.setGeometry(QtCore.QRect(10, 130, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(16)
        self.numSeven.setFont(font)
        self.numSeven.setObjectName("numSeven")
        self.numEight = QtWidgets.QPushButton(self.centralwidget)
        self.numEight.setGeometry(QtCore.QRect(90, 130, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(16)
        self.numEight.setFont(font)
        self.numEight.setObjectName("numEight")
        self.multiplyBtn = QtWidgets.QPushButton(self.centralwidget)
        self.multiplyBtn.setGeometry(QtCore.QRect(250, 200, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(16)
        self.multiplyBtn.setFont(font)
        self.multiplyBtn.setObjectName("multiplyBtn")
        self.numSix = QtWidgets.QPushButton(self.centralwidget)
        self.numSix.setGeometry(QtCore.QRect(170, 200, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(16)
        self.numSix.setFont(font)
        self.numSix.setObjectName("numSix")
        self.numFour = QtWidgets.QPushButton(self.centralwidget)
        self.numFour.setGeometry(QtCore.QRect(10, 200, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(16)
        self.numFour.setFont(font)
        self.numFour.setObjectName("numFour")
        self.numFive = QtWidgets.QPushButton(self.centralwidget)
        self.numFive.setGeometry(QtCore.QRect(90, 200, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(16)
        self.numFive.setFont(font)
        self.numFive.setObjectName("numFive")
        self.numOne = QtWidgets.QPushButton(self.centralwidget)
        self.numOne.setGeometry(QtCore.QRect(10, 270, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(16)
        self.numOne.setFont(font)
        self.numOne.setObjectName("numOne")
        self.numThree = QtWidgets.QPushButton(self.centralwidget)
        self.numThree.setGeometry(QtCore.QRect(170, 270, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(16)
        self.numThree.setFont(font)
        self.numThree.setObjectName("numThree")
        self.numTwo = QtWidgets.QPushButton(self.centralwidget)
        self.numTwo.setGeometry(QtCore.QRect(90, 270, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(16)
        self.numTwo.setFont(font)
        self.numTwo.setObjectName("numTwo")
        self.subtractBtn = QtWidgets.QPushButton(self.centralwidget)
        self.subtractBtn.setGeometry(QtCore.QRect(250, 270, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(16)
        self.subtractBtn.setFont(font)
        self.subtractBtn.setObjectName("subtractBtn")
        self.periodBtn = QtWidgets.QPushButton(self.centralwidget)
        self.periodBtn.setGeometry(QtCore.QRect(170, 340, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(16)
        self.periodBtn.setFont(font)
        self.periodBtn.setObjectName("periodBtn")
        self.numZero = QtWidgets.QPushButton(self.centralwidget)
        self.numZero.setGeometry(QtCore.QRect(10, 340, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(16)
        self.numZero.setFont(font)
        self.numZero.setObjectName("numZero")
        self.additionBtn = QtWidgets.QPushButton(self.centralwidget)
        self.additionBtn.setGeometry(QtCore.QRect(250, 340, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(16)
        self.additionBtn.setFont(font)
        self.additionBtn.setObjectName("additionBtn")
        self.equalBtn = QtWidgets.QPushButton(self.centralwidget)
        self.equalBtn.setGeometry(QtCore.QRect(250, 60, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(16)
        self.equalBtn.setFont(font)
        self.equalBtn.setObjectName("equalBtn")
        self.negPosBtn = QtWidgets.QPushButton(self.centralwidget)
        self.negPosBtn.setGeometry(QtCore.QRect(90, 340, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(16)
        self.negPosBtn.setFont(font)
        self.negPosBtn.setObjectName("negPosBtn")
        self.copyBtn = QtWidgets.QPushButton(self.centralwidget)
        self.copyBtn.setGeometry(QtCore.QRect(254, 20, 51, 23))
        self.copyBtn.setObjectName("copyBtn")
        Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 321, 21))
        self.menubar.setObjectName("menubar")
        Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Window)
        self.statusbar.setObjectName("statusbar")
        Window.setStatusBar(self.statusbar)

        self.retranslateUi(Window)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "Calculator"))
        self.clearBtn.setText(_translate("Window", "C"))
        self.delBtn.setText(_translate("Window", "Del"))
        self.divisionBtn.setText(_translate("Window", "/"))
        self.numNine.setText(_translate("Window", "9"))
        self.numSeven.setText(_translate("Window", "7"))
        self.numEight.setText(_translate("Window", "8"))
        self.multiplyBtn.setText(_translate("Window", "*"))
        self.numSix.setText(_translate("Window", "6"))
        self.numFour.setText(_translate("Window", "4"))
        self.numFive.setText(_translate("Window", "5"))
        self.numOne.setText(_translate("Window", "1"))
        self.numThree.setText(_translate("Window", "3"))
        self.numTwo.setText(_translate("Window", "2"))
        self.subtractBtn.setText(_translate("Window", "-"))
        self.periodBtn.setText(_translate("Window", "."))
        self.numZero.setText(_translate("Window", "0"))
        self.additionBtn.setText(_translate("Window", "+"))
        self.equalBtn.setText(_translate("Window", "="))
        self.negPosBtn.setText(_translate("Window", "+/-"))
        self.copyBtn.setText(_translate("Window", "Copy"))
